# File: netlify.toml

[build]
  command = "echo 'No build needed'"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Funciones
[functions]
  node_bundler = "esbuild"
  directory = "netlify/functions"

# Configuración de headers
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Content-Type = "application/json"
